# Generated by Django 5.2.7 on 2025-10-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.TextField()),
                ("processed_text", models.TextField(blank=True)),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("negative", "negative"),
                            ("neutral", "neutral"),
                            ("positive", "positive"),
                            ("", "unknown"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("region", models.CharField(blank=True, max_length=128)),
                ("product_category", models.CharField(blank=True, max_length=128)),
                ("gender", models.CharField(blank=True, max_length=16)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["date"], name="reviews_rev_date_c41c63_idx"),
                    models.Index(
                        fields=["region"], name="reviews_rev_region_28f5d7_idx"
                    ),
                    models.Index(
                        fields=["product_category"],
                        name="reviews_rev_product_bdcf70_idx",
                    ),
                    models.Index(
                        fields=["sentiment"], name="reviews_rev_sentime_2cb35a_idx"
                    ),
                ],
            },
        ),
    ]
